sudo: required
services: 
  - docker

before_install:
  - docker build -t jacobleesinger/docker-react -f Dockerfile.dev .

script:
  - docker run jacobleesinger/docker-react npm run test -- --coverage
