sudo: required
services: 
  - docker

before_install:
  - docker build -t jacobleesinger/docker-react -f Dockerfile.dev .

script:
  - docker run jacobleesinger/docker-react npm run ci-test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-038358933119"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $SECRET_ACCESS_KEY
